kind: Service
apiVersion: v1
metadata:
  name: webapp-service
spec:
  type: NodePort
  selector:
    app: webapp
  ports:
    - targetPort: 8080
      port: {{ .Values.service.port }}
      nodePort: 30080